### ISSUE TITLE
Melbs schedule

### ISSUE THREAD

**Issue by ajfisher** [nodebotsau/nodebotsau.github.io#6]
Add a schedule + key info to the site that comprises the following.

Needs to be relatively responsive so peeps can see it easily on their phone.

Schedule:

Atrium

*945-1015 - Registration
- 1030 - 1230 Build sessions
- 1230- 1300 Lunch
- 1300 - 1600 Build sessions
- 1600 - Science fair / Sumo Bot battle registration finishes
- 1630 - Sumo Bot Battle
- 1700 - Closing / finish up

Lecture Theatre
- 1015-1030 - Opening address
- 1030-1100 Intro to JS Hardware session
- 1130-1215 FloBots - Nick Moore, Social Robotics - Andrew Fisher (split these and put one first and one second)
- 1300-1415 Intro to Autonomous NodeBots - Andy Gelme, Quick computer vision - Andrey Sidorov, Going Wireless - Mark Wolfe (split these into 3 sessions)

BuzzConf Corner
- 1030 - 1230 (check with @rick) VR Cinema & 3D spiders
- 1300 - 1600 FloBots and 3D spiders

WiFi Details:

SSID: events@swin
Password: swin2016

Key links:

Team slack - nodebotsau.slack.com
Twitter - @nodebotsau

SimpleBot Repo: github.com/nodebotsau/simplebot
Scientist Kit Repo: https://github.com/nodebotsau/scientist-kit
Explorer Kit: https://github.com/ajfisher/jsiot-explorer

Johnny Five: http://johnny-five.io
ARDX: http://node-ardx.org

Hashtags #nodebotsday #nodebotsdaymelb

**Comment by rick** [comment]
![](https://assets.rbl.ms/1832033/980x.jpg)

**Comment by ajfisher** [comment]
LOL
